// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Random
{
    [RandomResourceType("random:index/pet:Pet")]
    public partial class Pet : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for
        /// more information.
        /// </summary>
        [Output("keepers")]
        public Output<ImmutableDictionary<string, string>?> Keepers { get; private set; } = null!;

        /// <summary>
        /// The length (in words) of the pet name. Defaults to 2
        /// </summary>
        [Output("length")]
        public Output<double> Length { get; private set; } = null!;

        /// <summary>
        /// A string to prefix the name with.
        /// </summary>
        [Output("prefix")]
        public Output<string?> Prefix { get; private set; } = null!;

        /// <summary>
        /// The character to separate words in the pet name. Defaults to "-"
        /// </summary>
        [Output("separator")]
        public Output<string> Separator { get; private set; } = null!;


        /// <summary>
        /// Create a Pet resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Pet(string name, PetArgs? args = null, CustomResourceOptions? options = null)
            : base("random:index/pet:Pet", name, args ?? new PetArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private Pet(string name, Input<string> id, PetState? state = null, CustomResourceOptions? options = null)
            : base("random:index/pet:Pet", name, state, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Pet resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Pet Get(string name, Input<string> id, PetState? state = null, CustomResourceOptions? options = null)
        {
            return new Pet(name, id, state, options);
        }
    }

    public sealed class PetArgs : global::Pulumi.ResourceArgs
    {
        [Input("keepers")]
        private InputMap<string>? _keepers;

        /// <summary>
        /// Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for
        /// more information.
        /// </summary>
        public InputMap<string> Keepers
        {
            get => _keepers ?? (_keepers = new InputMap<string>());
            set => _keepers = value;
        }

        /// <summary>
        /// The length (in words) of the pet name. Defaults to 2
        /// </summary>
        [Input("length")]
        public Input<double>? Length { get; set; }

        /// <summary>
        /// A string to prefix the name with.
        /// </summary>
        [Input("prefix")]
        public Input<string>? Prefix { get; set; }

        /// <summary>
        /// The character to separate words in the pet name. Defaults to "-"
        /// </summary>
        [Input("separator")]
        public Input<string>? Separator { get; set; }

        public PetArgs()
        {
        }
        public static new PetArgs Empty => new PetArgs();
    }

    public sealed class PetState : global::Pulumi.ResourceArgs
    {
        [Input("keepers")]
        private InputMap<string>? _keepers;

        /// <summary>
        /// Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for
        /// more information.
        /// </summary>
        public InputMap<string> Keepers
        {
            get => _keepers ?? (_keepers = new InputMap<string>());
            set => _keepers = value;
        }

        /// <summary>
        /// The length (in words) of the pet name. Defaults to 2
        /// </summary>
        [Input("length")]
        public Input<double>? Length { get; set; }

        /// <summary>
        /// A string to prefix the name with.
        /// </summary>
        [Input("prefix")]
        public Input<string>? Prefix { get; set; }

        /// <summary>
        /// The character to separate words in the pet name. Defaults to "-"
        /// </summary>
        [Input("separator")]
        public Input<string>? Separator { get; set; }

        public PetState()
        {
        }
        public static new PetState Empty => new PetState();
    }
}
